; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_deps =
	EEPROM
	mikalhart/TinyGPSPlus@^1.0.3
	vshymanskyy/TinyGSM@^0.11.5
	khoih-prog/ESP_AT_Lib@^1.5.1
	bblanchon/ArduinoJson@^6.21.2
	latimes2/InternalTemperature@^2.1.1-a
	https://github.com/sstaub/TeensyID
	https://github.com/firechip/Firechip_Quectel_EG25-G_Arduino_Library.git
	PubSubClient
	adafruit/Adafruit PN532@^1.3.1
	adafruit/Adafruit BusIO@^1.14.1
	https://github.com/tonton81/WDT_T4.git
